# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/clojure:1.11.1
    working_directory: ~/repo
    # resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # - run:
      #     name: Run JVM tests
      #     command: |
      #       script/test
      #       script/run_lib_tests
      - run:
          name: Create uberjar
          command: |
            script/build/uberjar
            RELEASE=/tmp/release
            script/ci/release                        
      - store_artifacts:
          path: /tmp/release
          destination: release
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}


workflows:
  version: 2
  ci:
    jobs:
      # - short-if-irrelevant
      # - jvm:
      #     requires:
      #        - short-if-irrelevant
      - deploy:
          # filters:
          #   branches:
          #     only: master
          # requires:
          #   - jvm

